In [1]:
import numpy as np

In [7]:
# python array : list
pylist = [1,2,3,4,5]
print(f"pylist: {pylist}")

pylist: [1, 2, 3, 4, 5]


In [9]:
# numpy array 
nplist = np.array(pylist)
print(f"nplist: {nplist};\nshape: {nplist.shape}")

nplist: [1 2 3 4 5];
shape: (5,)


In [19]:
nplist2 = np.reshape(nplist, (5,1))
nplist3 = np.reshape(nplist, (1,5))
print(f"nplist2: {nplist2};\nshape2: {nplist2.shape}")
print(f"nplist3: {nplist3};\nshape3: {nplist3.shape}")

nplist2: [[1]
 [2]
 [3]
 [4]
 [5]];
shape2: (5, 1)
nplist3: [[1 2 3 4 5]];
shape3: (1, 5)


In [35]:
nplist4 = np.array([[1,2,3,4,5]])
nplist5 = np.array([[1],[2],[3],[4],[5]])
print(f"nplist4: {nplist4};\nshape4: {nplist4.shape}")
print(f"nplist5: {nplist5};\nshape5: {nplist5.shape}")

nplist4: [[1 2 3 4 5]];
shape4: (1, 5)
nplist5: [[1]
 [2]
 [3]
 [4]
 [5]];
shape5: (5, 1)


In [36]:
print(nplist4[(0,0)])

1


In [37]:
print(np.dot(nplist4, nplist5))

[[55]]


In [39]:
nplist6 = np.array([[1,1,1], [0,0,0]])
print(nplist6)
print(np.transpose(nplist6))

[[1 1 1]
 [0 0 0]]
[[1 0]
 [1 0]
 [1 0]]
